app:
    resource: "@AppBundle/Controller/"
    type:     annotation
random_number:
    path: /lucky/number/{max}
    defaults:
        _controller: AppBundle:Lucky:number
        max: 100
    requirements:
        max: '\d+'
    methods: [GET,POST]
products:
    path: /products/
    defaults:
        _controller: AppBundle:Products:index
    methods: [GET]
products_new:
    methods: [GET, POST]
    path: /products/new
    defaults:
        _controller: AppBundle:Products:new
products_get:
    methods: [GET]
    path: /products/{id}
    defaults:
        _controller: AppBundle:Products:get
products_update:
    methods: [GET, POST]
    path: /products/update/{id}
    defaults:
        _controller: AppBundle:Products:update
products_reset:
    methods: [GET]
    path: /products/reset
    defaults:
        _controller: AppBundle:Products:reset
login:
    methods: [GET, POST]
    path: /login
    defaults:
        _controller: AppBundle:Login:index
logout:
    methods: [GET]
    path: /logout
    defaults:
        _controller: AppBundle:Logout:index