# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    foo: 'bar'
    db_path: 'sqlite:%kernel.root_dir%/../var/data.db'
#    parameter_name: value

services:
# can set defaults like this so autowire happens for all services
#    _defaults:
#        autowire: true
    product_repository:
        class: AppBundle\Repository\ProductRepository
        #autowire: true
        arguments:
            - '@app.guzzle'
            - '@logger'
            - '@serializer'
    app.pdo:
        class: PDO
        arguments:
            - "%db_path%"
        calls:
            - method: setAttribute
              arguments:
                  - '@= constant("PDO::ATTR_ERRMODE")'
                  - '@= constant("PDO::ERRMODE_EXCEPTION")'
    app.guzzle:
        class: GuzzleHttp\Client
        arguments: [{ base_uri: 'http://107.23.36.113', timeout: 20.0 }]
    app.user_agent_subscriber:
        class: AppBundle\Subscriber\UserAgentSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
#        arguments:
#            -
#               base_uri: 'http://107.23.36.113'
#               timeout: 3.0
    # not needed since this is included by default
    #app.logger:
    #    class: Monolog\Logger
    #    arguments: [{name: 'matts_logger'}]
    #app.serializer:
        #class: Symfony\Component\Serializer\Serializer
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
